//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.05 at 04:35:38 PM COT 
//


package com.novatronic.components.hsm.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for deployment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="deployment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hilos" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="llamadas" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deployment", propOrder = {
    "hilos",
    "llamadas"
})
public class Deployment {

    protected int hilos;
    protected int llamadas;

    /**
     * Gets the value of the hilos property.
     * 
     */
    public int getHilos() {
        return hilos;
    }

    /**
     * Sets the value of the hilos property.
     * 
     */
    public void setHilos(int value) {
        this.hilos = value;
    }

    /**
     * Gets the value of the llamadas property.
     * 
     */
    public int getLlamadas() {
        return llamadas;
    }

    /**
     * Sets the value of the llamadas property.
     * 
     */
    public void setLlamadas(int value) {
        this.llamadas = value;
    }

}
