//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.05 at 04:35:38 PM COT 
//


package com.novatronic.components.hsm.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hsmServer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hsmServer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="classModelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="modelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="classRequestName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="classResponseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idLMK" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="lenHeader" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="connectionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="timeout" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="intervalEcho" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="retriesNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="balanceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="percentWork" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="environmentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hsmServer", propOrder = {
    "id",
    "classModelName",
    "modelName",
    "classRequestName",
    "classResponseName",
    "idLMK",
    "lenHeader",
    "ip",
    "port",
    "connectionType",
    "timeout",
    "intervalEcho",
    "retriesNumber",
    "balanceType",
    "percentWork",
    "environmentType",
    "version"
})
public class HsmServer {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String classModelName;
    @XmlElement(required = true)
    protected String modelName;
    @XmlElement(required = true)
    protected String classRequestName;
    @XmlElement(required = true)
    protected String classResponseName;
    protected int idLMK;
    protected int lenHeader;
    @XmlElement(required = true)
    protected String ip;
    protected int port;
    @XmlElement(required = true)
    protected String connectionType;
    protected int timeout;
    protected int intervalEcho;
    protected int retriesNumber;
    @XmlElement(required = true)
    protected String balanceType;
    protected int percentWork;
    @XmlElement(required = true)
    protected String environmentType;
    protected int version;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the classModelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassModelName() {
        return classModelName;
    }

    /**
     * Sets the value of the classModelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassModelName(String value) {
        this.classModelName = value;
    }

    /**
     * Gets the value of the modelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the classRequestName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassRequestName() {
        return classRequestName;
    }

    /**
     * Sets the value of the classRequestName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassRequestName(String value) {
        this.classRequestName = value;
    }

    /**
     * Gets the value of the classResponseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassResponseName() {
        return classResponseName;
    }

    /**
     * Sets the value of the classResponseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassResponseName(String value) {
        this.classResponseName = value;
    }

    /**
     * Gets the value of the idLMK property.
     * 
     */
    public int getIdLMK() {
        return idLMK;
    }

    /**
     * Sets the value of the idLMK property.
     * 
     */
    public void setIdLMK(int value) {
        this.idLMK = value;
    }

    /**
     * Gets the value of the lenHeader property.
     * 
     */
    public int getLenHeader() {
        return lenHeader;
    }

    /**
     * Sets the value of the lenHeader property.
     * 
     */
    public void setLenHeader(int value) {
        this.lenHeader = value;
    }

    /**
     * Gets the value of the ip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIp() {
        return ip;
    }

    /**
     * Sets the value of the ip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIp(String value) {
        this.ip = value;
    }

    /**
     * Gets the value of the port property.
     * 
     */
    public int getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     */
    public void setPort(int value) {
        this.port = value;
    }

    /**
     * Gets the value of the connectionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectionType() {
        return connectionType;
    }

    /**
     * Sets the value of the connectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectionType(String value) {
        this.connectionType = value;
    }

    /**
     * Gets the value of the timeout property.
     * 
     */
    public int getTimeout() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     * 
     */
    public void setTimeout(int value) {
        this.timeout = value;
    }

    /**
     * Gets the value of the intervalEcho property.
     * 
     */
    public int getIntervalEcho() {
        return intervalEcho;
    }

    /**
     * Sets the value of the intervalEcho property.
     * 
     */
    public void setIntervalEcho(int value) {
        this.intervalEcho = value;
    }

    /**
     * Gets the value of the retriesNumber property.
     * 
     */
    public int getRetriesNumber() {
        return retriesNumber;
    }

    /**
     * Sets the value of the retriesNumber property.
     * 
     */
    public void setRetriesNumber(int value) {
        this.retriesNumber = value;
    }

    /**
     * Gets the value of the balanceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBalanceType() {
        return balanceType;
    }

    /**
     * Sets the value of the balanceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBalanceType(String value) {
        this.balanceType = value;
    }

    /**
     * Gets the value of the percentWork property.
     * 
     */
    public int getPercentWork() {
        return percentWork;
    }

    /**
     * Sets the value of the percentWork property.
     * 
     */
    public void setPercentWork(int value) {
        this.percentWork = value;
    }

    /**
     * Gets the value of the environmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnvironmentType() {
        return environmentType;
    }

    /**
     * Sets the value of the environmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnvironmentType(String value) {
        this.environmentType = value;
    }

    /**
     * Gets the value of the version property.
     * 
     */
    public int getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    public void setVersion(int value) {
        this.version = value;
    }

}
