//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.05 at 04:35:38 PM COT 
//


package com.novatronic.components.hsm.bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.novatronic.components.hsm.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ApiHSMConfig_QNAME = new QName("http://www.example.org/hsm-servers", "ApiHSMConfig");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.novatronic.components.hsm.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ApiHSMConfig }
     * 
     */
    public ApiHSMConfig createApiHSMConfig() {
        return new ApiHSMConfig();
    }

    /**
     * Create an instance of {@link HsmServer }
     * 
     */
    public HsmServer createHsmServer() {
        return new HsmServer();
    }

    /**
     * Create an instance of {@link Pool }
     * 
     */
    public Pool createPool() {
        return new Pool();
    }

    /**
     * Create an instance of {@link Servers }
     * 
     */
    public Servers createServers() {
        return new Servers();
    }

    /**
     * Create an instance of {@link Deployment }
     * 
     */
    public Deployment createDeployment() {
        return new Deployment();
    }

    /**
     * Create an instance of {@link General }
     * 
     */
    public General createGeneral() {
        return new General();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApiHSMConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/hsm-servers", name = "ApiHSMConfig")
    public JAXBElement<ApiHSMConfig> createApiHSMConfig(ApiHSMConfig value) {
        return new JAXBElement<ApiHSMConfig>(_ApiHSMConfig_QNAME, ApiHSMConfig.class, null, value);
    }

}
